[workspace]
resolver = "2"
members = [
	"build-info",
	"build-info-build",
	"build-info-common",
	"build-info-proc",
	"dependency-tree",
	"sample",
]

[workspace.package]
edition = "2021"
rust-version = "1.78.0"
