on:
  schedule:
    - cron: '23 2 * * 2'

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install `cargo-outdated`
        run: cargo install cargo-outdated
      - name: Check for necessary updates to `/Cargo.toml`
        run: cargo outdated -R --exit-code 1
